// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaKPyKtJ3_nabTaOik8I9MjxHzy2f-eAw',
    appId: '1:8317183196:web:c7c1e752d05dc1d64cc019',
    messagingSenderId: '8317183196',
    projectId: 'minqlite',
    authDomain: 'minqlite.firebaseapp.com',
    databaseURL: 'https://minqlite-default-rtdb.firebaseio.com',
    storageBucket: 'minqlite.appspot.com',
    measurementId: 'G-S8SFVQECMG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqZt16W7ff2Pw2edLQ-TH0PfIavzN1Spg',
    appId: '1:8317183196:android:b1a15c99d93abac44cc019',
    messagingSenderId: '8317183196',
    projectId: 'minqlite',
    databaseURL: 'https://minqlite-default-rtdb.firebaseio.com',
    storageBucket: 'minqlite.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq4K1UvgAFBJth7rwMQwQBncgKc4SXMbs',
    appId: '1:8317183196:ios:c9948899933274fb4cc019',
    messagingSenderId: '8317183196',
    projectId: 'minqlite',
    databaseURL: 'https://minqlite-default-rtdb.firebaseio.com',
    storageBucket: 'minqlite.appspot.com',
    iosClientId: '8317183196-65tbusi53kjv444viqj99h5hgnk2gc24.apps.googleusercontent.com',
    iosBundleId: 'com.example.demoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCq4K1UvgAFBJth7rwMQwQBncgKc4SXMbs',
    appId: '1:8317183196:ios:c9948899933274fb4cc019',
    messagingSenderId: '8317183196',
    projectId: 'minqlite',
    databaseURL: 'https://minqlite-default-rtdb.firebaseio.com',
    storageBucket: 'minqlite.appspot.com',
    iosClientId: '8317183196-65tbusi53kjv444viqj99h5hgnk2gc24.apps.googleusercontent.com',
    iosBundleId: 'com.example.demoapp',
  );
}
